apiVersion: v1
kind: Service
metadata:
  name: spin-deck
  namespace: spinnaker
  labels:
    app: spin
    stack: deck
spec:
  type: NodePort
  ports:
    - name: clouddriver
      port: 9000
      targetPort: 9000
  selector:
    load-balancer-spin-deck: "true"
