{%- from "spinnaker/map.jinja" import clouddriver with context -%}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-clouddriver-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: clouddriver
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: spin-clouddriver-v000
  template:
    metadata:
      labels:
        replication-controller: spin-clouddriver-v000
        load-balancer-spin-clouddriver: "true"
    spec:
      containers:
        - image: {{ clouddriver.image }}:{{ clouddriver.tag }}
          imagePullPolicy: Always
          name: clouddriver
          ports:
            - containerPort: 7002
              name: clouddriver
          volumeMounts:
            - mountPath: /opt/clouddriver/config
              name: spinnaker-config
            - mountPath: /root/.kube
              name: creds-config
            - mountPath: /root/.kubecreds
              name: kubernetes-config
          readinessProbe:
            httpGet:
              path: /credentials
              port: 7002
            initialDelaySeconds: 30
            timeoutSeconds: 2
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
        - name: creds-config
          secret:
            secretName: creds-config
        - name: kubernetes-config
          secret:
            secretName: kubernetes-config
