{%- from "spinnaker/map.jinja" import deck with context -%}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-deck-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: deck
    version: v000
spec:
  replicas: 1
  selector:
    matchLabels:
      replication-controller: spin-deck-v000
  template:
    metadata:
      labels:
        replication-controller: spin-deck-v000
        load-balancer-spin-deck: "true"
    spec:
      containers:
        - image: {{ deck.image }}:{{ deck.tag }}
          imagePullPolicy: Always
          name: deck
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    sleep 1 && sed -i 's@http://localhost:8084@/gate@' /opt/deck/html/settings.js
          env:
            - name: DECK_HOST
              value: "0.0.0.0"
            - name: DECK_PORT
              value: "9000"
            - name: API_HOST
              value: "http://spin-gate.spinnaker:8084"
          ports:
            - containerPort: 9000
              name: deck
          volumeMounts:
            - mountPath: /opt/deck/config
              name: spinnaker-config
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config