{%- from "spinnaker/map.jinja" import master, clouddriver with context -%}

redis:
  connection: redis://data-redis-server:6379
server:
  port: 7002
services:
  front50:
    baseUrl: http://spin-front50:8080
udf:
  enabled: false

aws:
  enabled: {{ clouddriver.aws.enabled }}
azure:
  enabled: {{ clouddriver.azure.enabled }}
cf:
  accounts:
  enabled: {{ clouddriver.cf.enabled }}
google:
  enabled: {{ clouddriver.google.enabled }}
credentials:
  challengeDestructiveActionsEnvironments: default
  primaryAccountTypes: default

default:
  account:
    env: {{ clouddriver.default.account.env }}


kubernetes:
  enabled: {{ master.providers.kubernetes.enabled }}
  accounts:
  {%- for acc in clouddriver.kubernetes.accounts %}
    - name: {{ acc.name }}
      user: {{ acc.user }}
      cluster: {{ acc.cluster }}
      namespaces:
        {%- for namespace in acc.namespaces %}
        - {{ namespace }}
        {%- endfor %}
      kubeconfigFile: {{ acc.kubeconfigFile }}
      dockerRegistries: # WARNING! only include configured accounts here
        {%- for dr in acc.dockerRegistries %}
        - accountName: {{ dr.accountName }}
        {%- endfor %}
  {%- endfor %}

dockerRegistry:
  enabled: {{ clouddriver.dockerRegistry.enabled }}
  accounts:
    {%- for acc in clouddriver.dockerRegistry.accounts %}
    - name: {{ acc.name }}
      address: {{ acc.address if acc.address != None else 'https://index.docker.io' }}
      repositories:
        {%- for repo in acc.repositories %}
        - {{ repo }}
        {%- endfor %}
    {%- endfor %}
