server:
  port: 8080

cassandra:
  enabled: false

redis:
  enabled: true

spinnaker:
  cassandra:
    enabled: false
  redis:
    enabled: true
    host: data-redis-server
    port: 6379


hystrix:
  command:
    default.execution.isolation.thread.timeoutInMilliseconds: 15000
  threadpool:
    DefaultNotificationDAO:
      coreSize: 25
      maxQueueSize: 100
    DefaultPipelineDAO:
      coreSize: 25
      maxQueueSize: 100