redis:
  connection: redis://data-redis-server:6379
server:
  port: 8084
services:
  clouddriver:
    baseUrl: http://spin-clouddriver:7002
  deck:
    baseUrl: http://spin-deck:9000
  front50:
    baseUrl: http://spin-front50:8080
  orca:
    baseUrl: http://spin-orca:8083
  igor:
    enabled: false
    baseUrl: http://spin-igor:8088
  rosco:
    enabled: false
    baseUrl: http://spin-rosco:8087