server:
  port: 8088

jenkins:
  enabled: false
  masters:
    - name: fake
      address: jenkins
      username: endpoint
      password: pass

travis:
  enabled: false

dockerRegistry:
  enabled: true

redis:
  connection: redis://data-redis-server:6379

services:
  clouddriver:
    baseUrl: http://spin-clouddriver:7002
  echo:
    baseUrl: http://spin-echo:8089