aws:
  enabled: false
docker:
  bakeryDefaults:
    targetRepository: spin-registry
  enabled: false
google:
  enabled: false
redis:
  connection: redis://spin-redis:6379
rosco:
  configDir: /opt/rosco/config/packer
server:
  port: 8087
